steps:
  #
  # Publish/package notifier
  #
  - label: ':docker: Prepare package.json'
    key: 'package-js'
    timeout_in_minutes: 3
    plugins:
      - docker-compose#v3.7.0:
          run: minimal-packager
    artifact_paths: min_packages.tar
  #
  - label: ':docker: Build CI image'
    key: 'ci-image'
    depends_on: 'package-js'
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.2.0:
          download: min_packages.tar
      - docker-compose#v3.7.0:
          build:
            - ci
          no-cache: true

  - label:  ':docker: Build node maze runner image'
    key: "node-maze-runner-image"
    depends_on: 'package-js'
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.3.0:
          download: min_packages.tar
      - docker-compose#v3.7.0:
          build:
            - node-maze-runner
          no-cache: true

  - label:  ':docker: Build browser maze runner image'
    key: "browser-maze-runner-image"
    depends_on: 'package-js'
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.3.0:
          download: min_packages.tar
      - docker-compose#v3.7.0:
          build:
            - browser-maze-runner
          no-cache: true

  - label: ':docker: Build CLI test image'
    key: 'cli-maze-image'
    depends_on: 'package-js'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          build: react-native-cli-tool-maze-runner
          no-cache: true