steps:

  #
  # Android builder
  #
  - label: ':docker: Build RN Android Builder image'
    key: 'android-builder-image'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.3.0:
          build: react-native-cli-android-builder
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:  react-native-cli-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}
      - docker-compose#v3.3.0:
          push: react-native-cli-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}

  #
  # Test fixtures
  #
  - label: ':android: Build RN 0.60 apk'
    key: 'rn-0-60-apk'
    depends_on:
      - 'android-builder-image'
    timeout_in_minutes: 60
    env:
      REACT_NATIVE_VERSION: rn0_60
    plugins:
      - docker-compose#v3.3.0:
          run: react-native-cli-android-builder
    artifact_paths:
      - build/rn0.60.apk

  - label: ':ios: Build RN 0.60 ipa'
    key: 'rn-0-60-ipa'
    timeout_in_minutes: 60
    agents:
      queue: 'opensource-mac-rn'
    env:
      REACT_NATIVE_VERSION: rn0_60
    artifact_paths: build/rn0.60.ipa
    commands:
      - npm run test:build-react-native-cli-ios
